services:
  desktop:
    image: hhansen06/docker-desktop
    build: .
    restart: always
    ports:
      - 80:6000
      - 81:6001
      - 9001:9001
    volumes:
      - ./chrome:/home/dockeruser/chrome
